### ISSUE TITLE
failing enum/union cases

### ISSUE THREAD

**Issue by ZuseZ4** [EnzymeAD/rust#11]
https://doc.rust-lang.org/beta/src/alloc/raw_vec.rs.html#448

https://doc.rust-lang.org/src/core/ptr/non_null.rs.html#197-203

**Comment by ZuseZ4** [comment]
```
#![feature(bench_black_box)]
use autodiff::autodiff;

enum Foo {
    a(f32),
    b(i32), 
}

#[autodiff(d_bar, Reverse, Active)]
fn bar(#[dup] x: &f32) -> f32 {
    let val: Foo = 
    if *x > 0.0 {
        Foo::a(*x)
    } else {
        Foo::b(12)
    };

    std::hint::black_box(&val);
    match val  {
        Foo::a(f) => f * f,
        Foo::b(_) => 4.0,
    }
}

fn main() {
    let x = 1.0;
    let mut dx = 2.0;
    let out = bar(&x);
    let dout = d_bar(&x, &mut dx, 1.0);
    println!("x: {out}");
}
```

**Comment by ZuseZ4** [comment]
Wip Explorer link: https://fwd.gymni.ch/9cLTiD

**Comment by ZuseZ4** [comment]
relatedly:
```
rustc: /h/292/drehwald/prog/rust/src/llvm-project/llvm/lib/Analysis/ScalarEvolution.cpp:8582: llvm::ScalarEvolution::ExitLimit llvm::ScalarEvolution::computeExitLimitFromSingleExitSwitch(const llvm::Loop*, llvm::SwitchInst*, llvm::BasicBlock*, bool): Assertion `L->contains(Switch->getDefaultDest()) && "Default case must not exit the loop!"' failed.
```

We probably want to fix the enums first, though.

**Comment by ZuseZ4** [comment]
[out2.ll.txt](https://github.com/EnzymeAD/rust/files/11023779/out2.ll.txt)

**Comment by wsmoses** [comment]
Oh I see the issue here.

The load side of the match gets compiled to be executed unconditionally. Therefore we think it's always safe to assume float.

**Comment by ZuseZ4** [comment]
Will check which pass it is. Tmp:
[afterPasses.ll.txt](https://github.com/EnzymeAD/rust/files/11023989/afterPasses.ll.txt)

**Comment by ZuseZ4** [comment]
notes:
EarlyCSEPass around line 500 removes the second load from the input `%x` and instead stores the previously read
