### ISSUE TITLE
eprintln! thread error

### ISSUE THREAD

**Issue by jpmedinagl** [EnzymeAD/rust#139]
When trying to autodiff a function that has the eprintln! macro, there is an error:
```
error: <unknown>:0:0: in function preprocess_eprintfunc void (): Enzyme: No create nofree of unknown value
@__cxa_thread_atexit_impl = extern_weak global i8
 at context:   call void @_ZN3std2io5stdio7_eprint17h1ff923295f510774E(ptr noalias nocapture noundef nonnull align 8 dereferenceable(48) %1) #110
 ```

I tried creating a minimal reproducible with ENZYME_OPT=1 and llvm-extract for the enzyme explorer ([out.txt](https://github.com/user-attachments/files/16382559/out.txt)) but the explorer gives a slightly different error
```
error: <unknown>:0:0: in function preprocess__ZN3std2io5stdio31print_to_buffer_if_capture_used17hf768171844a00e61E i1 (ptr): Enzyme: cannot compute with global variable that doesn't have marked shadow global
@_ZN3std2io5stdio14OUTPUT_CAPTURE7__getit5__KEY17h15828b3e0884a413E.llvm.11955502528429326793 = external hidden thread_local global <{ [8 x i8], [8 x i8], [1 x i8], [7 x i8] }>, align 8
```

Not sure if its the same error.

Below is the rust file and cargo. Generated the error with `cargo +enzyme build --release --bin file`

```
#![feature(autodiff)]

#[no_mangle]
#[autodiff(diff, Reverse)]
fn eprintfunc() {
    eprintln!("eprintln error");
}

fn main() {
    diff();
}
```

```
[package]
name = "lib"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "fat"

[[bin]]
name = "file"
path = "file.rs"
```

**Comment by wsmoses** [comment]
This should probably just be marked as inactive

**Comment by ZuseZ4** [comment]
https://github.com/EnzymeAD/Enzyme/blob/cdd8187ef4bea1e0d3daf61d8a19767cf8a95373/enzyme/Enzyme/ActivityAnalysis.cpp#L108

try if you can add it to one of these functions
