### ISSUE TITLE
Toolchain identifies as recent nighlty

### ISSUE THREAD

**Issue by marcpabst** [EnzymeAD/rust#149]
I suspect this is not really Enzyme-specific and not a super high-priority issue, but I realized that after following the instructions in the readme, the toolchain (or rather rustc) identifies as `rustc 1.77.0-nightly (53d9ae34a 2024-07-29)`, which then prompts some crates, in my case `memoffset`, to try and use unstable features (as they are already stabilized in Rust 1.77). E.g. `error[E0658]: use of unstable library feature 'offset_of'`. I'm not sure why that happens or if anything can be done about that...

Edit: It's `src/version` - any reason that's different from the actual version of the Rust compiler?

**Comment by ZuseZ4** [comment]
I reimplemented this fork on top of the latest master - https://github.com/EnzymeAD/rust/pull/162
I'll clean it up and make it the new master later today which should resolve this issue, please reopen if not.
