### ISSUE TITLE
How to do set custom gradient to return x in rust?

### ISSUE THREAD

**Issue by e99243506bigplay** [EnzymeAD/rust#20]
```
// #![feature(panic_unwind)]
#![feature(bench_black_box)]
// extern crate panic_unwind;
use autodiff::autodiff;

#[derive(Debug, Clone, PartialEq)]
struct Foo {
    x: f64,
    y: f64,
    r: f64
}

#[autodiff(dgrad, Reverse, Const)]
fn get_output(#[dup] amt: &mut f64, a: Foo, b: Foo) {
    {  
        // let t_amt = *t_amt;
        let ab = (*amt * a.r * a.y) / (a.x + *amt * a.r);
        let ba = (ab * b.r * b.x) / (b.y + ab * b.r);
        *amt = ba;
    }
}

fn main() {
    let b = Foo {
        x: 4848051834.0,
        y: 543430617.5,
        r: 0.997,
    };
    let a = Foo {
        x: 9907918868.0,
        y: 1127604104.0,
        r: 0.9985
    };


    let mut amt = 1.0;
    let mut amt2 = 1.0;
    let dg = dgrad(&mut amt, &mut amt2, a.clone(), b.clone());
    println!("amt: {amt:?}, amt2: {amt2:?}, dg: {dg:?}");
    let mut amt = 17321749.0;
    let mut amt2 = 1.0;
    let dg = dgrad(&mut amt, &mut amt2, a.clone(), b.clone());
    println!("amt: {amt:?}, amt2: {amt2:?}, dg: {dg:?}");
}
```

```
amt: 1.0107426332676432, amt2: 1.0107426329550588, dg: ()
amt: 17414541.144841213, amt2: 1.0000000098377733, dg: ()
```

as you see, when I input `amt` is `1.0` so function `dgrad` return the gradient is `1.0107426329550588`. is there anyway to `amt2 = 1.0;` then input `amt2` in function `dgrad` to return something like `17414541.144841213`?

or should I do this?

```
#[autodiff(dgrad, Reverse, Active)]
fn get_output(#[dup] amt: &mut f64, a: Foo, b: Foo) -> f64 {
    {  
        // let t_amt = *t_amt;
        let ab = (*amt * a.r * a.y) / (a.x + *amt * a.r);
        let ba = (ab * b.r * b.x) / (b.y + ab * b.r);
        ba
    }
}
```

```
let dg = dgrad(&mut amt, &mut amt2, a.clone(), b.clone(), 1.0);
println!("amt: {amt:?}, amt2: {amt2:?}, dg: {dg:?}");
let mut count = 0;
loop {
    amt2 = 0.0;
    let dg = dgrad(&mut amt, &mut amt2, a.clone(), b.clone(), 1.0);
    println!("amt: {amt:?}, amt2: {amt2:?}, dg: {dg:?}");
    amt = amt * amt2;
    if amt2 == 1.0 {
        break
    }
    count += 1;
}
println!("count: {count:?}");
```

Output:
```
...
amt: 17321764.990430593, amt2: 1.0000000000000004, dg: ()
amt: 17321764.9904306, amt2: 1.0000000000000004, dg: ()
amt: 17321764.99043061, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430616, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430623, amt2: 1.0000000000000004, dg: ()
amt: 17321764.99043063, amt2: 1.0000000000000004, dg: ()
amt: 17321764.99043064, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430646, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430653, amt2: 1.0000000000000004, dg: ()
amt: 17321764.99043066, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430668, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430675, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430683, amt2: 1.0000000000000004, dg: ()
amt: 17321764.99043069, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430698, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430705, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430713, amt2: 1.0000000000000004, dg: ()
amt: 17321764.99043072, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430728, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430735, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430743, amt2: 1.0000000000000004, dg: ()
amt: 17321764.99043075, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430757, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430765, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430772, amt2: 1.0000000000000004, dg: ()
amt: 17321764.99043078, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430787, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430795, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430802, amt2: 1.0000000000000004, dg: ()
amt: 17321764.99043081, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430817, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430824, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430832, amt2: 1.0000000000000004, dg: ()
amt: 17321764.99043084, amt2: 1.0000000000000004, dg: ()
amt: 17321764.990430847, amt2: 1.0000000000000002, dg: ()
amt: 17321764.99043085, amt2: 1.0000000000000002, dg: ()
amt: 17321764.990430854, amt2: 1.0000000000000002, dg: ()
amt: 17321764.990430858, amt2: 1.0000000000000002, dg: ()
amt: 17321764.99043086, amt2: 1.0000000000000002, dg: ()
amt: 17321764.990430865, amt2: 1.0000000000000002, dg: ()
amt: 17321764.99043087, amt2: 1.0000000000000002, dg: ()
amt: 17321764.990430873, amt2: 1.0000000000000002, dg: ()
amt: 17321764.990430877, amt2: 1.0000000000000002, dg: ()
amt: 17321764.99043088, amt2: 1.0000000000000002, dg: ()
amt: 17321764.990430884, amt2: 1.0000000000000002, dg: ()
amt: 17321764.990430888, amt2: 1.0, dg: ()
count: 4539
```

BTW, I am bad on math, pardon me. and graph calculator here: https://www.desmos.com/calculator/dd48dumucq

**Comment by e99243506bigplay** [comment]
After try to gather more infomation on it, I understand there is no way to make gradient to be equal to 1 directly, has be iterate step by step.

**Comment by ZuseZ4** [comment]
Hi @e99243506bigplay 
I am just on my phone and will have another look later today, but for the meantime a few hints.
1. The julia docs are currently the best enzyme frontend docs which we have. The Rust frontend is obviously a bit different, but at least the concept is the same: https://enzyme.mit.edu/index.fcgi/julia/stable/
2. For both Fwd. and Reverse mode we only allow returning a single float or (), aka nothing. If you have more complex returns, you'd need to pass them as mutable input args and mark them as dup.

**Comment by ZuseZ4** [comment]
Do these examples help you?  It shouws how to use reverse mode when having a vector (or struct) input and a float output (passed as mutable input arg here).

https://enzyme.mit.edu/index.fcgi/julia/stable/generated/autodiff/

I would recommend you to use either your second example where you return f64, or follow the julia example.
Your first approach is quite complex. you use amt as input and as an output variable at the same time. It will be much easier to get this right if you have an amt1 as input and an amt2 as output. In that case you would mark both amt1 and amt2 as dup. 
The shadow of amt1 would be initalized to 0, since we will add the gradient to it. the shadow of amt2 would be initalized to 1.0, sinmilar to how they do it for the output y in the julia example

**Comment by ZuseZ4** [comment]
Do you think you could re-formulate your problem given the separated in and out variables, as shown above?
Then I might understand better what you try to achieve. 
It is however getting quite late over here, so I can't promise that I'll be able to help you tonight.

**Comment by e99243506bigplay** [comment]
> Do you think you could re-formulate your problem given the separated in and out variables, as shown above? Then I might understand better what you try to achieve. It is however getting quite late over here, so I can't promise that I'll be able to help you tonight.

```
// #![feature(panic_unwind)]
#![feature(bench_black_box)]
// extern crate panic_unwind;
use autodiff::autodiff;

#[derive(Debug, Clone, PartialEq)]
struct Foo {
    x: f64,
    y: f64,
    r: f64
}

#[autodiff(dgrad, Reverse, Const)]
fn get_output(#[dup] amt_in: & f64, #[dup] amt_out: &mut f64, a: Foo, b: Foo) {
    {  
        let ab = (*amt_in * a.r * a.y) / (a.x + *amt_in * a.r);
        let ba = (ab * b.r * b.x) / (b.y + ab * b.r);
        *amt_out = ba;
    }
}

fn main() {
    let b = Foo {
        x: 4848051834.0,
        y: 543430617.5,
        r: 0.997,
    };
    let a = Foo {
        x: 9907918868.0,
        y: 1127604104.0,
        r: 0.9985
    };


    let mut amt_in = 17321749.0;
    let mut d_amt_in = 0.0;
    let mut amt_out = 0.0;
    let mut b_amt_out = 1.0;
    let dg = dgrad(&amt_in, &mut d_amt_in, &mut amt_out, &mut b_amt_out, a.clone(), b.clone());
    println!("amt_in: {d_amt_in:?}, d_amt_in: {d_amt_in:?}, amt_out: {amt_out:?}, b_amt_out: {b_amt_out:?}, dg: {dg:?}");
    //let mut amt = 17321749.0;
    //let mut amt2 = 1.0;
    //let dg = dgrad(&mut amt, &mut amt2, a.clone(), b.clone());
    //println!("amt: {amt:?}, amt2: {amt2:?}, dg: {dg:?}");
}
```
When amt_in is assigned be 17321749, the amt_out or call it as gradient is ~1.

`amt_in: 1.0000000098377733, d_amt_in: 1.0000000098377733, amt_out: 17414541.144841213, b_amt_out: 0.0, dg: ()`
![a](https://user-images.githubusercontent.com/113240403/231369816-5a9ba8b5-87a5-4d3f-9407-ae5c762e8b39.png)

That is the approx solution of "d/dx g(f(x)) = 1" or "d/dx h(x) = 0", and I need the `x` what number is.
I am try to find a way to set gradient of unknown function j, something like "d/dx j(x) = y" that y I could set 1 or 0 or another vaiue, for example, https://www.wolframalpha.com/input?i2d=true&i=Divide%5Bd%2Cdx%5Dx*x+%3D+3.25 if I set y is equal to 3.25, then I should get x is equal to 1.625 and get the variable x.

so, if I assign `amt_in` is 1 on above code, I will get:
`amt: 1.0107426329550588, amt2: 1.0107426332676432, dg: ()`
that answer is not I want. I want `amt2` to be equal 1, then `amt` should be ~17321749.

...wait, The code you provided, why d_amt_in is become constant in this code snippet? I couldn't calculate the gradient from newton method such of that.
```
loop {
    dgrad(&amt_in, &mut d_amt_in, &mut amt_out, &mut b_amt_out, a.clone(), b.clone());
    println!("amt_in: {amt_in:?}, d_amt_in: {d_amt_in:?}, amt_out: {amt_out:?}, b_amt_out: {b_amt_out:?}, dg: {dg:?}");
    amt_in = amt_in * 2;
    if d_amt_in <= 1.0 {
        break
    }
}
```

 Any way, I need a function in rust that could calculate unknown function j, "d/dx j(x) = y" that y I could change be any I want be.

**Comment by e99243506bigplay** [comment]
I will close the issue until I understand the Automation Differential Concept, then I will open again...

**Comment by e99243506bigplay** [comment]
That seems like, I forgot to differentiate the original equation, that probably is why I unable to get solution value.
