### ISSUE TITLE
Macro Design

### ISSUE THREAD

**Issue by ZuseZ4** [EnzymeAD/rust#32]
Let's collect some opinions on our current macro design to see if there is some common design that people would rather use than our current options:

1) 
It's fine that we disagree, but to summarize my point (which may well be misguided):

- I think code should strive to be readable without putting unnecessary expectations on the reader.
- There are several layers of code understanding. The first step is understanding the syntax and the structure of the code. I think here the second variant makes it much easier to understand the syntax.
- I haven't yet seen any significant drawbacks for the second variant, which is why I'm suggesting that this might be a better "default". There may very well be drawbacks I'm not aware of though.

**Comment by ZuseZ4** [comment]
As per zulip discussion we will remove the Return activity in cases where a function returns (), since we anyhow only accept const there and it might confuse users to have to annotate a not existing return.

**Comment by OwenTrokeBillard** [comment]
I peeked at the unreleased [Rust Enzyme book](https://github.com/EnzymeAD/rustbook) and took notice of the macro syntax.

The current syntax is:
```rust
#[autodiff(df, Reverse, Active, Active, Active)]
fn f(x: f32, y: f32) -> f32 {
  x * x + 3.0 * y
}
```

Have you considered putting the activity declarations next to the arguments? That way it is clear which declarations are associated with which arguments. Something like:
```rust
#[autodiff(df, Reverse, Active)]
fn f(#[active] x: f32, #[active] y: f32) -> f32 {
  x * x + 3.0 * y
}
```

On another note, the book looks great so far. Excellent work as usual.

**Comment by jedbrown** [comment]
That is in fact supported and I prefer it. I believe for technical reasons, we can't/don't support those inline attributes on the return type.

**Comment by jedbrown** [comment]
And a word of warning, there are a few syntax bugs in the book currently. I'll fix them (using `mdbook test`) as soon as the new rebase is ready.

**Comment by ZuseZ4** [comment]
I am mostly without internet till end of year, I'll answer in more details in the first days of January. The inline syntax is supported, unless you apply multiple autodiff macros to the same function.
