### ISSUE TITLE
init enzyme submodule

### ISSUE THREAD

**Issue by ZuseZ4** [EnzymeAD/rust#34]
We now use enzyme as a submodule rather than subtree.
As a consequence we need to manually init the enzyme submodule.
We should check where other submodules are registered, to allow x.py to handle that automatically when required.

**Comment by bytesnake** [comment]
Fixed (and checked) in https://github.com/EnzymeAD/rust/commit/5408863ebe0d7c88ed28d53a284e5ee3a5095e0f
